### ISSUE TITLE
Antialiasing support : broken?

### ISSUE THREAD

**Issue by Maxx1234** [residualvm/residualvm#1149]
Forcing antialiasing through driver control panel does not work with Residual v0.2.0.
Tested on Win7-32bit & WinXP-32bit with GTX760 and the latest nVidia drivers.
Antialiasing with ResidualVM v0.1.1 works fine on the same system.

**Comment by somaen** [comment]
Does setting antialiasing through residualvm.ini work?

**Comment by Maxx1234** [comment]
Unfortunately no.

Also, I had the chance to test this on Ubuntu 10.04-64bit with GTX650Ti, with the same results.

**Comment by Botje** [comment]
This is probably due to the recent fullscreen changes.
Before, the game was rendered directly to screen at 640x480.
Now, the game is rendered to a 640x480 off-screen buffer and scaled up to your native screen resolution.
I see two solutions:
- render the game at a resolution bigger than the screen and scale to fit.
- perform anti-aliasing on the off-screen buffer, but still render at 640x480.

I don't know how the driver-forced anti-aliasing works exactly, but I think the first solution will yield a cleaner image. It does require some work from the engines though.

**Comment by aquadran** [comment]
I would rather avoid first solution

**Comment by andrews05** [comment]
Just found this problem running EMI in fullscreen. Wouldn't it be better to start by rendering at your native screen resolution, then worry about anti-aliasing after? Always rendering at 640x480 is rather limiting, especially with UHD/HiDPI screens becoming more common.

**Comment by Napper64** [comment]
I believe this issue has been fixed in the latest builds (not sure what commit). Setting anti-aliasing through residualvm.ini works again for me.

**Comment by bgK** [comment]
Right, it was fixed by #1250.

**Comment by andrews05** [comment]
Yup, looks good! Is it possible to make it render at higher resolutions?
