### ISSUE TITLE
 Support for Kheops Studio games

### ISSUE THREAD

**Issue by ivanbraidi** [residualvm/residualvm#1233]
In these days I tried to replay some old games from Kheops Studio and I discovered that all their games have an issue with modern nvidia graphic drivers on Win 7 and more modern versions of the os. Long story short all the graphic part of the games is not working anymore, so all the games are unplayable (I tested them even on a virtual Win 98 machine, but there is no way to play these good games anymore).

So, I thinked that would be a very great thing to add the Kheops Engine in ResidualVM.

Here is the complete game list of Kheops Studio:

- The Egyptian Prophecy (2004)
- Crystal Key 2 (2004)
- Return to Mysterious Island (2005)
- ECHO: Secrets of the Lost Cavern (2005)
- Voyage: Inspired by Jules Verne (2005)
- The Secrets of Da Vinci: The Forbidden Manuscript (2006)
- SafeCracker The Ultimate Puzzle Adventure (2006)
- Destination Treasure Island (2006)
- Cleopatra a Queen's Destiny (2007)
- Nostradamus: The Last Prophecy (2007)
- Dracula 3 - The Path of the Dragon (2008)
- Return to Mysterious Island II (2009)
- The Fall Trilogy: Separation (2009)
- The Fall Trilogy 2: Reconstruction (2010)
- The Fall Trilogy 3: Revelation (2011)

And here is a useful link for further infos:

https://en.wikipedia.org/wiki/Kheops_Studio

Thank you very much for your great job!! ResidualVM is WONDERFUL!! ;)

**Comment by Botje** [comment]
Can you say with any certainty that these games share an engine? If they do, that's certainly a good motivator for someone to attempt this.

**Comment by Nitrus** [comment]
Judging from http://wiki.xentax.com/index.php?title=CyroBF (The URL is misleading, it's actually CryoBF), you can see that several of them share the same file formats. At least the Jusles Verne inspired ones do.
Some more internet "research" to suggest that they use the same engine can be seen here:
https://bugs.winehq.org/show_bug.cgi?id=20947

If I'm to guess, I'd say at least these three use it:
- Return to Mysterious Island (2005)
- ECHO: Secrets of the Lost Cavern (2005)
- Voyage: Inspired by Jules Verne (2005)

...also one that I don't see in the list:
- Versailles II: the Testament of the King

I'd assume they share an engine, or subsets of the same engine.

It seems many of them have multiple platform ports (including iOS and Macintosh), which may be something that needs to be considered.
That being said, save for Return for Mysterious island and the Dracula games ( all of them seem to share a developer) which can be found on GOG, the others might be difficult to find.

On a sidenote, Microids/Anuman seem to have developed Syberia 1 & 2 as well, though I doubt it's the same engine.

**Comment by somaen** [comment]
In general, implementing a game engine for ResidualVM is a huge effort, and requires quite a fair bit of spare time, as well as the motivation to use that spare time to implement such an engine. Thus, requests for engines aren't really effective unless they come with an offer to do at least a decent amount of the work, or the relevant original source code is offered.

Which is why I take a similar stance to that used by ScummVM; we do not take _requests_ for engines. (Simply because it's hard to say if anyone will implement it, and thus our tracker would fill up with such requests faster than we could handle them, which is not very fast at all).

That being said, we do however want people to discuss the games they wish for, and perhaps inspire each other to put some effort into making it happen. To that end we have a thread in our forum where people have been discussing what games they were wishing for:
http://forums.residualvm.org/viewtopic.php?f=1&t=144

I'd suggest either following this discussion there, or creating a new thread for that matter. 

I'm closing this issue for the above mentioned reasons, and hope to see a fruitful discussion about these games in our forums.
