### ISSUE TITLE
STARK: Monkey eye cannot be swapped

### ISSUE THREAD

**Issue by neuromancer** [residualvm/residualvm#1253]
Hi, i'm playing The Longest Journey using revision 867f2e2c981e33410b90d2385d61ad81b8539e7e,

In chapter 3, when you have to swap the monkey eye, it seems to be impossible (yes, the lights are off). This is not blinking when i try to use it with the real eye. 
Find [attached](https://github.com/residualvm/residualvm/files/317091/tlj-win-038.txt) a saved game when you can reproduce it (rename to .tlj).

**Comment by bgK** [comment]
Hi,

Using your save, I've been able to swap the eyes. The sensitive zone of the monkey eye seems to be a little wrong. You need to click a bit lower and right than the glass eye.

![capture d ecran de 2016-06-16 06-43-46](https://cloud.githubusercontent.com/assets/52294/16105733/c4d4ad92-338d-11e6-888d-5a1da240c22b.png)

While there is indeed a bug here, I'm closing this since only game breaking bugs are accepted for now.

**Comment by neuromancer** [comment]
It works!, thanks for checking it.
