### ISSUE TITLE
MYST3: Some bugs in game

### ISSUE THREAD

**Issue by ctoroman** [residualvm/residualvm#1400]
1. J'nanin. Obstructed leverage control (save1)
[save1.zip](https://github.com/residualvm/residualvm/files/1734594/save1.zip)

2. Voltaic. When drawing a symbol, there is no pencil sound on paper (save2)
[save2.zip](https://github.com/residualvm/residualvm/files/1734600/save2.zip)

3. Easter eggs in the game works only with the English keyboard layout (press "~"). On a different layout, they do not work. In the original game, the keyboard layout does not change and the eggs always work.

4. In the folder with ResidualVM, the OGLdpf.log file appears, which is not deleted when the emulator is removed (sorry for offtopic)

**Comment by dafioram** [comment]
Whats wrong with the controls for item 1 (maybe an annotated picture)?

**Comment by ctoroman** [comment]
When the levers are deflected up or down, right or left, the image in the round window is stuck. I have to move the levers several times. In the original game it works smoothly.

**Comment by bgK** [comment]
1. Thanks for your report this is now fixed.
2. The scripts explicitly set the volume for that sound very low. I believe it is intentional.
3. This is a duplicate of #1373. Which can't be fixed because the event system in ResidualVM does not allow to refer to a key by its position on the keyboard.
4. Looks like a problem on your system. ResidualVM does not create / use that file. Perhaps your graphics drivers are creating it.
