### ISSUE TITLE
SDL: Improve mapping of game controllers in GRIME

### ISSUE THREAD

**Issue by lmerckx** [residualvm/residualvm#1411]
Since the game controller support in ResidualVM, some keys are not available anymore.

For instance, the "skip scene" is now mapped over SDL_CONTROLLER_BUTTON_GUIDE (which is not always present). The menu is associated to SDL_CONTROLLER_BUTTON_RIGHTSTICK (not very intuitive).

Can we improve that ?
My proposition is:
- support "special" buttons directly in resvm-sdl-events.cpp (example: open virtual keyboard)
- in engine classes (grim.cpp or grim_controls.cpp): map SDL2 controller button codes to correct KEY_JOY1_B? value. This will need to add new event types: EVENT_CONTROLLERAXIS_MOTION, EVENT_CONTROLLERBUTTON_DOWN, ... 

What do you think about it ?

**Comment by lmerckx** [comment]
I can do the dev for this issue. But my intention was to share the proposition to get feedback.

**Comment by bgK** [comment]
Sorry for the late reply.

A few years ago a "keymapper" was added to ScummVM / ResidualVM. It's unfinished, and currently not very usable. But the ultimate goal, IMO, is to have things working in the following way:
* Each engine exposes a list of possible actions for each game (Menu, take item, use, skip scene, ...), and default bindings for keyboard and mouse.
* Each backend declares a list of available input devices / keys.
* Each backend has the possibility to override / add to the default bindings for each game.
* A GUI dialog allows the user to customize the action / key bindings.

This is a long term goal. But perhaps one to keep in mind when designing short term solutions so that they don't go in too conflicting directions.

Your proposal seems good to me. Bonus points if you can avoid duplicating the special key handing between `sdl-events.cpp` and `resvm-sdl-events.cpp`.

**Comment by lmerckx** [comment]
@bgK Ok, I nearly developped the above proposition.
But, I still have an issue with the virtual keyboard:
Indeed, the "resvm-sdl-events" needs to know if virtual keyboard is opened to emulate mouse events instead of joystick one.
But it is currently not accessible outside "default-events" which creates it.

Do you think it is acceptable to convert VirtualKeyboard as a singleton with global object (g_vkeybd) ?
It works this way, but I should propose this modification to ScummVM. Will it be accepted ?

**Comment by lmerckx** [comment]
@bgK Or maybe I can test "CursorMan.isVisible()" which indicates (for GrimE games) that the virtual keyboard is opened ?
Very easier solution and ResidualVM only.

**Comment by lmerckx** [comment]
Ok, I took some time to work on it.
 
A merge request has been created for this issue: https://github.com/residualvm/residualvm/pull/1520
