### ISSUE TITLE
STARK: version info here instead of actual version is shown in the main menu

### ISSUE THREAD

**Issue by Faalagorn** [residualvm/residualvm#1439]
Judging by the comment at #1415 I think it is a known issue, but since that PR is now merged and there's no related issue, I thought I'll make one.

When starting any game (tested with Steam, steam demo, GOG and retail demo), the `version info here`  string is shown instead of actual version info (copyright sign, year, company, build, …).

See more [this comment](1415#issuecomment-389440278) for more info.

* Information about the game: The Longest Journey, all versions (tested on GOG, Steam, Steam demo, retail demo)
* Language of game: English
* Platform: Linux

**Comment by DouglasLiuGamer** [comment]
Yeah, I am aware of this. I have added this one to the project here: https://github.com/residualvm/residualvm/projects/1#card-9934456

**Comment by Faalagorn** [comment]
I saw that TODO note, but wasn't aware what that *info and message box* was actually that thing :smile: . I noticed that so far you're only adding the actual pull requests as references, but if you don't mind, you can add this issue as a reference there as well, so other people looking at it will get an idea what it is as well.

**Comment by DouglasLiuGamer** [comment]
Implemented in #1467

**Comment by Faalagorn** [comment]
I noticed the cursor changes when you hover it over the "©1999 Funcom" string, as it'd be a clickable element. Just noticed it now, not sure if it behaved like that in the older versions and whether or not the cursor changes in the original game?

Too bad the actual version info can not be displayed though. Is it a good idea to hardcode the build versions as well as the string? (for example based on checksum check on EXE or some data files), or even display a residualVM version there?

**Comment by DouglasLiuGamer** [comment]
@Faalagorn 

> the cursor changes when you hover it over the "©1999 Funcom" string

Yes, the original game also behaves like this. I made efforts in ensuring that. Actually, in many places of menus, the cursor will change on texts that are not clickable. That makes it easier to implement the changing mechanism anyway. The only exception is the video replay menu, where the cursor **doesn't** change on video titles and I have to handle this case explicitly. Can't understand why the original game made this.

About the version info, according to @bgK it is hard-coded in the original executable so we don't have a way to extract it. Based on what I know, we cannot expect that the user can provide the EXE since ResidualVM only needs the game's data files, and the data files are not related to the version info. ResidualVM is not a **part** of TLJ so it feels wired to have its version number in the game, IMO.
