### ISSUE TITLE
STARK: Swedish CD version does not have any "AllowFF" / "AllowFFHelp" widgets.

### ISSUE THREAD

**Issue by eriktorbjorn** [residualvm/residualvm#1470]
If I start the Swedish CD version (which currently requires some changes to the source code, see Issue #1469) and open the settings menu, it prints the following warning messages:

````
Unable to find render entry with name 'AllowFF' in location 'OptionLocation'
Unable to find render entry with name 'AllowFFHelp' in location 'OptionLocation'
````

Normally I'd consider the harmless, but looking at the source code I get the impression that it will add the widgets anyway. So perhaps they should be disabled to avoid potentially undefined behavior?

**Comment by DouglasLiuGamer** [comment]
This is a known fact. I am pretty sure that this is harmless since a widget without a render entry cannot be triggered in all implemented cases. I just leave that text as an indicator. Well since there is a fix to do anyway I think I can manually disable them, just in case.

ResidualVM can support fast forwarding (disabled by default) no matter what version the game is.
