### ISSUE TITLE
TINYGL: Doesn't render correctly on RISC OS

### ISSUE THREAD

**Issue by ccawley2011** [residualvm/residualvm#1515]
(originally mentioned as part of #1507)

On RISC OS, there's a noticeable issue with rendering where parts of the screen don't get updated, as pictured below:

![image](https://user-images.githubusercontent.com/19293424/51803733-39905880-2250-11e9-9c34-9fad11d21e97.png)
![image](https://user-images.githubusercontent.com/19293424/51803738-4745de00-2250-11e9-89cd-b7382c10d4ac.png)

The screenshots were taken with `TGL_DIRTY_RECT_SHOW` defined in `graphics/tinygl/zdirtyrect.cpp`, which produces the rectangles around the parts of the screen that do get updated.

**Comment by vpelletier** [comment]
Quick self-introduction: I worked on TinyGL and especially dirtyrects recently, although I am the original author of neither. I believe dirtyrects came from a GSoC contributor, but it was not in a good enough state to be enabled by default. I fixed bugs until it did not cause any (known) regression.

On to the debugging: How does residualvm looks with `--no-dirtyrects` ?

You may want to start debugging with grim, as monkey island does more advanced rendering in-engine rather than at TinyGL level IIRC.

Just in case the bug disappears when disabling dirtyrects, here is a quick introduction: dityrects work by comparing the OpenGL draw calls issued by the engine between consecutive frames:
- Each draw call in a frame provides its screen-space bounding rectangle, telling where it has any effect on the screen, until the engine tells the GL to render the frame.
- Then, calls of the previous and current frames are compared, and the bounding rectangles of all differing calls are kept (both the one from previous frame and the one from current one).
- Then, these rectangles are aggregated, with the objective to find a sweet spot between many small rectangles covering just the pixels actually needing a redraw and few very large rectangles covering a lot of unchanged area.
- Then, each call of the frame is rendered with each final bounding rectangle, allowing the code actually doing the rendering to skip unchanged pixels, providing a nice performance boost on most frames.
- Finally, current frame's call chain is swapped wit previous frame's, previous frame's is emptied and TinyGL is ready to receive calls for the next frame.

So overal, even if it is rather long to describe, it should rely on rather basic operations - as long as C++ is happy with the architecture it should be pretty safe. There is maybe one place which may require some attention: `LinearAllocator`, from `zgl.h`.

**Comment by ccawley2011** [comment]
> On to the debugging: How does residualvm looks with --no-dirtyrects ?

Unfortunately, that option makes no difference.

**Comment by vpelletier** [comment]
Checking the hq scene more in grim, I am not sure I understand what is missing: does the slideshow eventually appears, or is it always the blank wall ?

**Comment by ccawley2011** [comment]
This problem occurs on Android as well, so this might be an issue common to ARM-based systems.

> Checking the hq scene more in grim, I am not sure I understand what is missing: does the slideshow eventually appears, or is it always the blank wall ?

The slideshow only appears when the in-game menu is opened with F1, however when the slide changes, the slide disappears but won't reappear. None of the characters move, except for Eva, whose model only gets partially redrawn.

**Comment by mparnaudeau** [comment]
@ccawley2011 You mentioned in pull request that it fixed this issue. Are there remaining problems? Should this issue be closed?
