### ISSUE TITLE
The longest Journey. computer police station

### ISSUE THREAD

**Issue by ogromanas** [residualvm/residualvm#1551]
In the computer of the police station, it only allows to select the Jacob McAllen item in window mode. In full screen it can not be selected.
![IMG_20190601_191918](https://user-images.githubusercontent.com/2190247/58751712-768c8600-84a2-11e9-8b1e-6b8550e74735.jpg)
![IMG_20190601_191850](https://user-images.githubusercontent.com/2190247/58751718-8d32dd00-84a2-11e9-8dac-59b035dc8699.jpg)

**Comment by bgK** [comment]
Thank you for your report. Could you please attach the file named `gui.ini` from your game folder? It contains configuration for the fonts used by the game that will be useful for debugging.

**Comment by ogromanas** [comment]
[TEXT95]
bigfont=Slurry
bigheight=19
smallfont=Garamond
smallheight=12

font0 = Folkard
fontsize0 = 20
font1 = Folkard
fontsize1 = 12
font2 = Arial
fontsize2 = 11
font3 = Bradley Hand ITC
fontsize3 = 14
font4 = Bradley Hand ITC
fontsize4 = 20
font5 = Bradley Hand ITC
fontsize5 = 16
font6 = Bradley Hand ITC
fontsize6 = 15
font7 = Florentine Script
fontsize7 = 13

**Comment by Zaerei** [comment]
I've determined that restoring any missing fonts in the `fonts` folder will fix this issue. I haven't tested this *too* thoroughly, so I don't know if it's related to a fallback because of missing fonts, or if the fonts *must* be the defaults, but as soon as I hunted down and installed all the missing fonts I could inspect the name properly.
