### ISSUE TITLE
STARK/TLJ: Text truncation.

### ISSUE THREAD

**Issue by ZanderTenoki** [residualvm/residualvm#1702]
OS: Xubuntu 20.04 LTS
ResidualVM: 0.4.0git (Sept 5 2020 01:06:29)
TLJ version: GOG
Problem:
In most circumstances the game's text gets randomly truncated. Which by I mean two random character gets replaced by three periods (or an ellipsis). The only way to prevent the the bug is to set the game to run in windowed mode in the original resulotion and the font anti-aliasing turned on.
Here is a screenshot for illustration:
![TLJ_text_bug](https://user-images.githubusercontent.com/70880698/92360049-80ad2380-f0ec-11ea-9241-ffaeee6a523b.png)

**Comment by Tailszefox** [comment]
Got the same issue on both Windows 10 and Debian 10.

I had a look around and managed to isolate the issue to commit d5304e25687106a659c5b7f966d4f8eb6628930c (ie., version from commit acd114234f7875c5139f8677fceb67b239d71795 does not have the issue). But due to the sheer size of that commit I wasn't able to isolate a particular change.

However, I looked around some more and saw that some functions for drawing text accepted a "useEllipsis" argument. I found the function used here: https://github.com/residualvm/residualvm/blob/015caa2313a5c9ea473dc6cf546ccedba69c7cf9/engines/stark/visual/text.cpp#L288

So I changed it to the following by adding two arguments at the end:
```cpp
font->drawString(&surface, lines[i], 0, scaledLineHeight * i, surface.w, white, _align, 0, false);
```
The second to last argument is "deltax", which I have no idea about, so I just put 0. The last argument is the "useEllipsis" I mentioned, which I have set to false since it is true by default. With that, the ellipses are gone and the text is displayed correctly.

I'm not going to pretend I found the definitive solution, like I said I'm not familiar enough with the codebase, but hopefully this can help narrow down the issue and create an actual fix.

**Comment by vmedea** [comment]
I've noticed the same issue on Ubuntu 20.04 Focal. At the default window size it's okay (just very small) but when I resize the window to make it bigger, or use full-screen mode, more and more … appear in the subtitles, item descriptions, menu items and so on.
