### ISSUE TITLE
GRIM: Manny can't walk past the bone wagon when getting the key in the Petrified Forest

### ISSUE THREAD

**Issue by somaen** [residualvm/residualvm#676]
After going down the tunnel, and getting of the car, Manny is unable to squeeze past the bone wagon to get the key. This makes it necessary to drive back to the previous screen, walk to the key, get it, and then walk back to the bone wagon.

ResidualVM 0.1.0-branch, OpenGL-renderer. (Mac OS X)
https://dl.dropbox.com/u/12443522/grimsaves/grim05.gsv
This issue was reported in the testing-thread in the forums.

**Comment by eblanca** [comment]
I won't open a new issue, because this is strictly related.
With latest residualvm snapshot (branch 0.3x) I also experienced a further (unwanted?) blocking situation.
After breaking the pumping trees, I was able to reach the demon beavers gate on the bon wagon WITHOUT passing through the tunnel, so I had no key at all. Then, I couldn't jump back on the bone wagon to reach the wood arrow and get the key.
