### ISSUE TITLE
GRIM: Maintenance demon's face shading problem

### ISSUE THREAD

**Issue by RyanJWilliams** [residualvm/residualvm#755]
Only seems to happen when he opens his mouth in this scene. Otherwise it looks normal.

![residualvm 2013-09-29 21-41-42-20](https://f.cloud.github.com/assets/5575257/1236209/d73f5dc8-29b9-11e3-836b-94162edafed1.png)

![residualvm 2013-09-29 21-41-43-35](https://f.cloud.github.com/assets/5575257/1236213/eade120c-29b9-11e3-927d-8daee4148ae4.png)

DxDiag: http://pastebin.com/4QKSxbvK

**Comment by vpelletier** [comment]
Replaying the HD edition (...re-bought in a recent HIB), I noticed they also have this bug:
![image](https://user-images.githubusercontent.com/191204/32526144-b64d3914-c41f-11e7-8b99-1d129ef64ecc.png)
This was taken with the "new renderer" mode, not the "original renderer".

So... data issue ?

**Comment by Napper64** [comment]
This is a data issue. The problem is with the vertices associated with one of the faces of the jaw mesh  in models "br_head2.3do" + "br_head3.3do". I wrote something quick to swap the jaw meshes for the ones in model node "br_head1" and it solved the issue.

Sadly its quite a hacky solution so I won't be committing it. For anyone interested here's the code below in **Model.cpp**. 

![image](https://user-images.githubusercontent.com/17673124/36512182-2c0ee0e6-1761-11e8-9dcf-36e4b41f3973.png)
![image](https://user-images.githubusercontent.com/17673124/36512304-c5f4680c-1761-11e8-842e-3611a464019e.png)
